### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by JustChapman** [dinhquochan/nova-phpcs#2]
Nova: 1.0
phpcs plugin: 1.2
phpcs (via composer): PHP_CodeSniffer version 3.5.6 (stable) by Squiz (http://www.squiz.net)

I'm seeing a parse error in the debug pane when editing a php file:

> Extension encountered an uncaught exception:
> /Users/blablablah/Library/Application Support/Nova/Extensions/dinhquochan.phpcs/Scripts/main.min.js (Line 1, Column 0)
> SyntaxError: JSON Parse error: Unexpected identifier "ERROR"
> 	parse@[native code]
> file:///Users/blablablah/Library/Application%20Support/Nova/Extensions/dinhquochan.phpcs/Scripts/main.min.js:1:411

Running ~/.composer/vendor/bin/phpcs /path/to/file.php works as expected in the cli. 

**EDIT: This ended up being due to having a dash in the standard name in preferences.** I might suggest you include a link to the phpcs docs at https://github.com/squizlabs/PHP_CodeSniffer and/or a note how that string should be formatted??

Also, I don't know if this can be done easily but, it would be really great if you could have a validate button, similar to how PHPStorm is configured. It allows you to see if the phpcs binary is correctly configured.

**Comment by 314mic** [comment]
Same here.

**Comment by dinhquochan** [comment]
Fixed. Thanks

Please update version to 1.3.0
