### ISSUE TITLE
[Feature Request] Per-project standard

### ISSUE THREAD

**Issue by redgluten** [dinhquochan/nova-phpcs#8]
Hi and thanks for the great work here. 👌

I’m working on projects using different standards (PSR-2, Drupal…) and thus would need an easy way to declare it on a per-project basis rather than having to switch it though the extension preferences.

Is this possible with Nova current APIs? I might work on a PR if it can be done.

**Comment by jbeales** [comment]
Howdy!  This was merged a few days ago as part of #3. I don't know if it's been deployed to the extension library yet, or if anything needs to be done to deploy it.

**Comment by redgluten** [comment]
Awesome, thanks 😀
