### ISSUE TITLE
Looking for a maintainer nova-phpcs!

### ISSUE THREAD

**Issue by dinhquochan** [dinhquochan/nova-phpcs#9]
Hi,

I not to buy Nova.app, so I can not update this extension anymore.
If someone can update and maintain this extension, DM me contact@dinhquochan.com

Thanks.

**Comment by reykjalin** [comment]
This extension wasn't working for me, and I ended up [creating another](https://extensions.panic.com/extensions/com.thorlaksson/com.thorlaksson.phpcs/) that does, and is _sligthly_ more configurable.

Feel free to direct people there 🙂 .

And thank you for the work you put into this extension! It was a helpful baseline to go off for the one I created ☺️

**Comment by dinhquochan** [comment]
@reykjalin Thanks.
